services:
  - type: web
    name: talkera-connect
    runtime: node
    plan: free
    rootDir: BackEnd
    buildCommand: npm ci && npm ci --include=dev --prefix FrontEnd && npm run build --prefix FrontEnd
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        sync: false
      - key: JWT_TOKEN
        generateValue: true
